# which go to the model you want to use
cfg_root: "/home/firo/workspace/FieldRobotSense/experiment_result/pointpillar.yaml"

# which go to the .pth
model_path: "/home/firo/workspace/FieldRobotSense/experiment_result/checkpoint_epoch_80.pth"

# pointcloud_topic in the bag if you are not sure
# rosbag info xxx.bag check the topic name
pointcloud_topic: "/velodyne_points" # default is from kitti2bag: /velodyne_points

# only the predict probablity over this threshold will be draw a box
threshold: 0.7

viz_rate: 1.0